version: '3.8'
services:
  orion-db:
    image: mysql:5.6
    container_name: orion-db
    restart: always
    volumes:
      - orion:/var/lib/mysql
      - ./database/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./database/:/docker-entrypoint-initdb.d/
    ports:
      - 127.0.0.1:7900:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 15s
      retries: 3
  orion-server:
    container_name: orion-ms
    image: orion-ms
    environment:
      - ENV=prod
    extra_hosts:
      - orion-public:${PUBLIC_IP}
    depends_on:
      orion-db:
        condition: service_healthy
    volumes:
      - ./config:/config
    ports:
      - 8484:8484
      - 8585-8590:8585-8590
      - 8799:8799
volumes:
  orion:
