debug: false
database:
  url: jdbc:mysql://127.0.0.1:7900/orion?autoReconnect=true
  user: root
  password: root
socket:
  provider: networking.netty.NettySocketProvider
  # provider: networking.mina.MinaSocketProvider
login:
  key: releaselogin
  host: 127.0.0.1
  serverName: Scania  # Name of the Server
  eventMessage: Welcome to Maple Story Global. # Event Message at Channel Selection
  flag: 3 # Flag at Channel Selection  0: Nothing 1: Event 2: New 3: Hot
  userlimit: 100 # total user limit of the server

world:
  # Rates
  exp: 1
  meso: 1
  drop: 1
  cash: 0
  adminOnly: false # Admin Only or not
  flags: 0 # 1 :  Disable PQ 0 :  Enable PQ
  serverMessage: Maple Story V90 # Server Scrolling Message
channel:
  host: 127.0.0.1
  count: 2
  events:
    - 3rdjob # 3rd Job event
    - elevator # Ludibrium Elevator
    - Boats #  Boat Between Ellinia and Orbis
    - Geenie # Boat between Orbis and Ariant
    - Cabin # Boat Orbis to Leafre
    - Trains # Trains between Orbis and Ludibrium
    - Hak # Hak that travel between Orbis, Mu Lung and Herb Town
    - AirPlane # AirPlane between KC and CBD
    - Subway  # Subway Train between Kerning City and New Leaf City
#    - 2095_tokyo
#    - 4jberserk
#    - 4jrush
#    - Amoria
#    - AriantPQ1
#    - AriantPQ2
#    - AriantPQ3
#    - ArkariumBattle
#    - Aufhaven
#    - BossBalrog_EASY
#    - BossBalrog_NORMAL
#    - BossHunterPQ
#    - BossQuest
#    - BossQuestEASY
#    - BossQuestHARD
#    - BossQuestHELL
#    - BossQuestMed
#    - Brawler
#    - CathedralWedding
#    - ChaosHorntail
#    - ChaosZakum
#    - Christmas
#    - CoreBlaze
#    - cpq
#    - cpq2
#    - CWKPQ
#    - CygnusBattle
#    - DLPracticeField
#    - DollHouse
#    - Dragonica
#    - Dunas
#    - Dunas2
#    - ElementThanatos
#    - Ellin
#    - ElnathPQ
#    - English
#    - English0
#    - English1
#    - English2
#    - enterDisguise3
#    - FireDemon
#    - Ghost
#    - GuildQuest
#    - Gunslinger
#    - HenesysPQ
#    - HontalePQ
#    - HontaleSquad
#    - HorntailBattle
#    - Iceman
#    - Juliet
#    - Kenta
#    - KerningPQ
#    - LudiMazePQ
#    - LudiPQ
#    - LumpEnergy
#    - MesoMap
#    - MiniDungeon
#    - MonsterPark
#    - MulungParty
#    - MV
#    - NamelessMagicMonster
#    - Olivia
#    - OmegaPQ
#    - OrbisPQ
#    - PigTown
#    - PinkBeanBattle
#    - Pirate
#    - PiratePQ
#    - ProtectTylus
#    - Ravana_EASY
#    - Ravana_HARD
#    - Ravana_HELL
#    - Ravana_MED
#    - Relic
#    - rescueGaga
#    - Rex
#    - Romeo
#    - s4aWorld
#    - s4nest
#    - s4resurrection
#    - s4resurrection2
#    - ScarTarBattle
#    - ServerMessage
#    - Subway
#    - TimeMachinePart
#    - Vergamot
#    - Visitor
#    - WitchTower_EASY
#    - WitchTower_Hard
#    - WitchTower_Med
#    - ZakumAltar
#    - ZakumBattle
#    - ZakumPQ
